# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '5edf6369-8c8f-4792-b95a-a91ff0ae10f8'
  imageRepository: 'ncplproject'
  containerRegistry: 'ncplcr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/website/dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  pool: Default

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'website/dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'ncplcr'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'